/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Unaise988CreateInput } from "./Unaise988CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateUnaise988Args {
  @ApiProperty({
    required: true,
    type: () => Unaise988CreateInput,
  })
  @ValidateNested()
  @Type(() => Unaise988CreateInput)
  @Field(() => Unaise988CreateInput, { nullable: false })
  data!: Unaise988CreateInput;
}

export { CreateUnaise988Args as CreateUnaise988Args };
