/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Unaise988WhereUniqueInput } from "./Unaise988WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Unaise988UpdateInput } from "./Unaise988UpdateInput";

@ArgsType()
class UpdateUnaise988Args {
  @ApiProperty({
    required: true,
    type: () => Unaise988WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Unaise988WhereUniqueInput)
  @Field(() => Unaise988WhereUniqueInput, { nullable: false })
  where!: Unaise988WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Unaise988UpdateInput,
  })
  @ValidateNested()
  @Type(() => Unaise988UpdateInput)
  @Field(() => Unaise988UpdateInput, { nullable: false })
  data!: Unaise988UpdateInput;
}

export { UpdateUnaise988Args as UpdateUnaise988Args };
