/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { US } from "./US";
import { USCountArgs } from "./USCountArgs";
import { USFindManyArgs } from "./USFindManyArgs";
import { USFindUniqueArgs } from "./USFindUniqueArgs";
import { DeleteUSArgs } from "./DeleteUSArgs";
import { USService } from "../us.service";
@graphql.Resolver(() => US)
export class USResolverBase {
  constructor(protected readonly service: USService) {}

  async _usItemsMeta(
    @graphql.Args() args: USCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [US])
  async usItems(@graphql.Args() args: USFindManyArgs): Promise<US[]> {
    return this.service.usItems(args);
  }

  @graphql.Query(() => US, { nullable: true })
  async us(@graphql.Args() args: USFindUniqueArgs): Promise<US | null> {
    const result = await this.service.us(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => US)
  async deleteUS(@graphql.Args() args: DeleteUSArgs): Promise<US | null> {
    try {
      return await this.service.deleteUs(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
